// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXw4vYu3-WjvZawRi4iQ1p3XIHiwJhI94',
    appId: '1:455342987983:web:45dd9d28589f82878eb5ba',
    messagingSenderId: '455342987983',
    projectId: 'mynotes-proj-julz',
    authDomain: 'mynotes-proj-julz.firebaseapp.com',
    storageBucket: 'mynotes-proj-julz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB97HxNKe-zL0FZkBSkwXxJeHst1i3iG8I',
    appId: '1:455342987983:android:fe25de119938a6428eb5ba',
    messagingSenderId: '455342987983',
    projectId: 'mynotes-proj-julz',
    storageBucket: 'mynotes-proj-julz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuI9uI8WU-mr193c2TAA1CqwSOHDO93wc',
    appId: '1:455342987983:ios:695b194f586f82818eb5ba',
    messagingSenderId: '455342987983',
    projectId: 'mynotes-proj-julz',
    storageBucket: 'mynotes-proj-julz.appspot.com',
    iosClientId: '455342987983-2qj7vb1qm5lgeoah7hcdk2id3q1s7rto.apps.googleusercontent.com',
    iosBundleId: 'com.juliuzllanillo.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuI9uI8WU-mr193c2TAA1CqwSOHDO93wc',
    appId: '1:455342987983:ios:695b194f586f82818eb5ba',
    messagingSenderId: '455342987983',
    projectId: 'mynotes-proj-julz',
    storageBucket: 'mynotes-proj-julz.appspot.com',
    iosClientId: '455342987983-2qj7vb1qm5lgeoah7hcdk2id3q1s7rto.apps.googleusercontent.com',
    iosBundleId: 'com.juliuzllanillo.mynotes',
  );
}
